=== embrace-io/embrace-android-sdk/embrace-config-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "JSON Schema definition for the Embrace configuration file.",
  "id": "https://json.schemastore.org/embrace-config-schema-1.0.0.json",
  "properties": {
    "app_id": {
      "description": "Your 5 character app ID.",
      "type": "string",
      "maxLength": 5,
      "minLength": 5
    },
    "api_token": {
      "description": "Your API 32-hexdigit token.",
      "type": "string",
      "maxLength": 32,
      "minLength": 32
    },
    "ndk_enabled": {
      "description": "Enables NDK crash capture",
      "default": true,
      "type": "boolean"
    },
    "sdk_config": {
      "type": "object",
      "properties": {
        "automatic_data_capture": {
          "type": "object",
          "properties": {
            "memory_info": {
              "description": "Enables memory warning capture",
              "default": true,
              "type": "boolean"
            },
            "power_save_mode_info": {
              "description": "Enables power save mode capture.",
              "default": true,
              "type": "boolean"
            },
            "network_connectivity_info": {
              "description": "Enables network connectivity capture.",
              "default": true,
              "type": "boolean"
            },
            "anr_info": {
              "description": "Enables ANR capture.",
              "default": true,
              "type": "boolean"
            }
          },
          "minProperties": 1
        },
        "taps": {
          "type": "object",
          "properties": {
            "capture_coordinates": {
              "description": "Set to false to disable capturing tap coordinates.",
              "default": true,
              "type": "boolean"
            }
          },
          "minProperties": 1
        },
        "view_config": {
          "type": "object",
          "properties": {
            "enable_automatic_activity_capture": {
              "description": "Enables capturing activity lifecycle changes in breadcrumbs.",
              "default": true,
              "type": "boolean"
            }
          },
          "minProperties": 1
        },
        "webview": {
          "type": "object",
          "properties": {
            "capture_query_params": {
              "description": "Set to false to disable capturing of web view query parameters. If webview:enable is set to false, this setting has no effect since all capture of web view information is disabled.",
              "default": true,
              "type": "boolean"
            },
            "enable": {
              "description": "Set to false to disable capturing of web views.",
              "default": true,
              "type": "boolean"
            }
          },
          "minProperties": 1
        },
        "crash_handler": {
          "type": "object",
          "properties": {
            "enabled": {
              "description": "Set to false to prevent the SDK from connecting to the uncaught exception handler.",
              "default": true,
              "type": "boolean"
            }
          },
          "minProperties": 1
        },
        "compose": {
          "type": "object",
          "properties": {
            "capture_compose_onclick": {
              "description": "Enables capture of Jetpack Compose click events.",
              "default": false,
              "type": "boolean"
            }
          },
          "minProperties": 1
        },
        "capture_fcm_pii_data": {
          "description": "Enables PII data within FCM capture.",
          "default": false,
          "type": "boolean"
        },
        "networking": {
          "type": "object",
          "properties": {
            "default_capture_limit": {
              "description": "Default capture limit for specified domains.",
              "default": 1000,
              "type": "integer"
            },
            "domains": {
              "description": "List of domain names and their respective limits.",
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "domain_name": {
                    "description": "Domain URL.",
                    "type": "string"
                  },
                  "domain_limit": {
                    "description": "Limit for the number of requests to be tracked.",
                    "type": "integer"
                  }
                },
                "minProperties": 1
              },
              "minItems": 1,
              "uniqueItems": true
            },
            "capture_request_content_length": {
              "description": "Disable capture of network length which can interfere with certain streaming network requests.",
              "default": true,
              "type": "boolean"
            },
            "disabled_url_patterns": {
              "description": "Specify one or more regular expressions to exclude network request with URLs matching one of the regular expressions from being captured.",
              "type": "array",
              "items": {
                "type": "string"
              },
              "minItems": 1,
              "uniqueItems": true
            },
            "enable_native_monitoring": {
              "description": "Enable capture of network requests made using the native Java network API.",
              "default": true,
              "type": "boolean"
            },
            "enable_network_span_forwarding": {
              "description": "Enables network span forwarding.",
              "default": false,
              "type": "boolean"
            },
            "url_redaction_patterns": {
              "description": "List of regex pattern strings for URLs that should be redacted (capturing groups are redacted).",
              "type": "array",
              "items": {
                "type": "string"
              },
              "minItems": 1,
              "uniqueItems": true
            }
          },
          "minProperties": 1
        },
        "capture_public_key": {
          "type": "string",
          "description": "Declares the key that should be used to capture network request bodies, if any."
        },
        "sensitive_keys_denylist": {
          "description": "List of sensitive keys whose values should be redacted on capture.",
          "type": "array",
          "items": {
            "type": "string"
          },
          "minItems": 1,
          "uniqueItems": true
        },
        "anr": {
          "type": "object",
          "properties": {
            "capture_unity_thread": {
              "description": "Enables Unity ANR capture.",
              "default": false,
              "type": "boolean"
            }
          },
          "minProperties": 1
        },
        "app": {
          "type": "object",
          "properties": {
            "report_disk_usage": {
              "description": "The SDK collects the disk usage for the app. You can disable this if your app has a large number of local files to prevent excessive resource usage, especially on lower-end devices.",
              "default": true,
              "type": "boolean"
            }
          },
          "minProperties": 1
        },
        "background_activity": {
          "type": "object",
          "properties": {
            "capture_enabled": {
              "description": "Enables background activity capture.",
              "default": false,
              "type": "boolean"
            }
          },
          "minProperties": 1
        },
        "base_urls": {
          "type": "object",
          "properties": {
            "config": {
              "description": "Base config URL for the SDK.",
              "type": "string"
            },
            "data": {
              "description": "Base data URL for the SDK.",
              "type": "string"
            }
          },
          "minProperties": 1
        },
        "session": {
          "type": "object",
          "properties": {
            "components": {
              "description": "Allowlist of session components that should be included in the session payload. The presence of this property denotes that the gating feature is enabled.",
              "type": "array",
              "items": {
                "type": "string"
              },
              "uniqueItems": true
            },
            "send_full_for": {
              "description": "List of events allowed to send a full session payload if the gating feature is enabled.",
              "type": "array",
              "items": {
                "type": "string"
              },
              "minItems": 1,
              "uniqueItems": true
            }
          },
          "minProperties": 1
        },
        "sig_handler_detection": {
          "description": "Enables 3rd party signal handler detection.",
          "default": true,
          "type": "boolean"
        },
        "app_exit_info": {
          "type": "object",
          "properties": {
            "aei_enabled": {
              "description": "Enables Application Exit Info capture.",
              "default": true,
              "type": "boolean"
            }
          },
          "minProperties": 1
        },
        "app_framework": {
          "type": "string",
          "description": "Project's app framework, one of react_native, unity, flutter or native."
        }
      },
      "minProperties": 1
    },
    "unity": {
      "type": "object",
      "properties": {
        "symbols_archive_name": {
          "description": "Custom file name for unity symbols",
          "type": "string"
        }
      },
      "minProperties": 1
    }
  },
  "title": "Embrace Config Schema",
  "type": "object"
}

=== embrace-io/embrace-android-sdk/embrace-gradle-plugin/src/test/resources/config_file_expected.json
{
  "app_id": "sazwW",
  "api_token": "13f327e891ad45858949004eb755b9f1",
  "ndk_enabled": true,
  "sdk_config": {
    "crash_handler": {
      "enabled": true
    },
    "networking": {
      "capture_request_content_length": false,
      "url_redaction_patterns": [
        "https://example.com/(secret)"
      ]
    },
    "taps": {
      "capture_coordinates": false
    }
  }
}

=== embrace-io/embrace-android-sdk/embrace-gradle-plugin-integration-tests/src/test/resources/config-overrides.json
{
  "app_id": "abcde",
  "api_token": "12345123451234512345123451234512",
  "ndk_enabled": false,
  "sdk_config": {
    "app_framework": "flutter",
    "base_urls": {
      "config": "https://config.example.com",
      "data": "https://data.example.com"
    },
    "sensitive_keys_denylist": [
      "secret"
    ],
    "capture_public_key": "my_public_key",
    "networking": {
      "default_capture_limit": 54,
      "disabled_url_patterns": [
        "google.com",
        "example.com"
      ],
      "domains": [
        {
          "domain_name": "example.com",
          "domain_limit": 30
        }
      ],
      "capture_request_content_length": true,
      "enable_native_monitoring": false,
      "enable_network_span_forwarding": true,
      "url_redaction_patterns": [
        "https://example.com/(secret)"
      ]
    },
    "automatic_data_capture": {
      "network_connectivity_info": false,
      "power_save_mode_info": false,
      "anr_info": false,
      "ui_load_tracing_disabled": true,
      "ui_load_tracing_selected_only": true,
      "end_startup_with_app_ready": true
    },
    "anr": {
      "capture_unity_thread": true
    },
    "view_config": {
      "enable_automatic_activity_capture": false
    },
    "compose": {
      "capture_compose_onclick": true
    },
    "taps": {
      "capture_coordinates": true
    },
    "app": {
      "report_disk_usage": false
    },
    "crash_handler": {
      "enabled": false
    },
    "app_exit_info": {
      "aei_enabled": false
    },
    "sig_handler_detection": true,
    "background_activity": {
      "capture_enabled": true
    },
    "webview": {
      "enable": false,
      "capture_query_params": false
    },
    "capture_fcm_pii_data": true
  }
}
